#!/bin/bash
source scripts/load-env-file.sh

ENV_FILE=$1
IMAGE_TAG=$2

load_env_file

docker build . -t ${IMAGE_TAG} \
  --build-arg VUE_APP_FACEBOOK_URL="$VUE_APP_FACEBOOK_URL" \
  --build-arg VUE_APP_INSTAGRAM_URL="$VUE_APP_INSTAGRAM_URL" \
  --build-arg VUE_APP_TWITTER_URL="$VUE_APP_TWITTER_URL" \
  --build-arg VUE_APP_GITHUB_URL="$VUE_APP_GITHUB_URL" \
  --build-arg VUE_APP_EMAIL_URL="$VUE_APP_EMAIL_URL" \
  --build-arg VUE_APP_WEBSITE_TITLE_FONTFAMILY="$VUE_APP_WEBSITE_TITLE_FONTFAMILY" \
  --build-arg VUE_APP_WEBSITE_FAVICON_URL="$VUE_APP_WEBSITE_FAVICON_URL" \
  --build-arg VUE_APP_WEBSITE_LOGO_URL="$VUE_APP_WEBSITE_LOGO_URL" \
  --build-arg VUE_APP_WEBSITE_TITLE="$VUE_APP_WEBSITE_TITLE" \
  --build-arg VUE_APP_WEBSITE_DESCRIPTION="$VUE_APP_WEBSITE_DESCRIPTION" \
  --build-arg VUE_APP_WEBSITE_VIDEO_URL="$VUE_APP_WEBSITE_VIDEO_URL" \
  --build-arg VUE_APP_WEBSITE_BACKGROUND_COLOR="$VUE_APP_WEBSITE_BACKGROUND_COLOR" \
  --build-arg VUE_APP_WEBSITE_COLOR="$VUE_APP_WEBSITE_COLOR" \
  --build-arg VUE_APP_HIDE_WEBSITE_FOOTER="$VUE_APP_HIDE_WEBSITE_FOOTER" \
  --build-arg VUE_APP_BACKGROUND_IMAGE_URL="$VUE_APP_BACKGROUND_IMAGE_URL" \
  --build-arg VUE_APP_ANALYTICS_ID="$VUE_APP_ANALYTICS_ID"
