{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "agapanto-under-construction.serviceAccountName" . }}
  labels:
{{ include "agapanto-under-construction.labels" . | indent 4 }}
{{- end -}}
