#!/bin/bash
source load-env-file.sh

ENV_FILE=.env.local
IMAGE_TAG=agapanto-under-construction:latest

load_env_file

docker build . -t ${IMAGE_TAG} \
  --build-arg FACEBOOK_URL="$VUE_APP_FACEBOOK_URL" \
  --build-arg INSTAGRAM_URL="$VUE_APP_INSTAGRAM_URL" \
  --build-arg TWITTER_URL="$VUE_APP_TWITTER_URL" \
  --build-arg GITHUB_URL="$VUE_APP_GITHUB_URL" \
  --build-arg EMAIL_URL="$VUE_APP_EMAIL_URL" \
  --build-arg WEBSITE_TITLE_FONTFAMILY="$VUE_APP_WEBSITE_TITLE_FONTFAMILY" \
  --build-arg WEBSITE_FAVICON_URL="$VUE_APP_WEBSITE_FAVICON_URL" \
  --build-arg WEBSITE_LOGO_URL="$VUE_APP_WEBSITE_LOGO_URL" \
  --build-arg WEBSITE_TITLE="$VUE_APP_WEBSITE_TITLE" \
  --build-arg WEBSITE_DESCRIPTION="$VUE_APP_WEBSITE_DESCRIPTION" \
  --build-arg WEBSITE_VIDEO_URL="$VUE_APP_WEBSITE_VIDEO_URL" \
  --build-arg WEBSITE_BACKGROUND_COLOR="$VUE_APP_WEBSITE_BACKGROUND_COLOR" \
  --build-arg WEBSITE_COLOR="$VUE_APP_WEBSITE_COLOR" \
  --build-arg HIDE_WEBSITE_FOOTER="$VUE_APP_HIDE_WEBSITE_FOOTER" \
  --build-arg BACKGROUND_IMAGE_URL="$VUE_APP_BACKGROUND_IMAGE_URL"
